version: '3'

services:
  django: &django
    build: .
    command:
      "gunicorn --bind 0.0.0.0:8000 \
      --worker-class=gevent --workers=3 --threads=6 \
      --timeout=600 --graceful-timeout=600 \
      --log-level=DEBUG \
      inspection_planner.wsgi:application"
    ports:
      - 8000
    env_file:
      - ./.envs/prod/django
    volumes:
      - static_volume:/usr/src/app/static

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - django

volumes:
  static_volume:
