version: '3'

services:
  django: &django
    build: .
    command:
      gunicorn inspection_planner.wsgi:application --bind 0.0.0.0:8000 --worker-class=gevent --workers=3 --threads=6 --log-level=INFO
    ports:
      - 8000
    env_file:
      - ./.envs/prod/django
    volumes:
      - static_volume:/usr/src/app/static

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    volumes:
      - static_volume:/usr/src/app/static
    depends_on:
      - django

volumes:
  static_volume:
