# Generated by Django 2.2.3 on 2019-07-12 10:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewYorkBridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.FloatField()),
                ('bin', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=100)),
                ('local_bridge', models.CharField(max_length=25)),
                ('region', models.CharField(max_length=10)),
                ('county_name', models.CharField(max_length=254)),
                ('political_field', models.CharField(max_length=100)),
                ('carried', models.CharField(max_length=50)),
                ('crossed', models.CharField(max_length=50)),
                ('crossed_mi', models.CharField(max_length=50)),
                ('crossed_to', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=25)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('primary_owner', models.CharField(max_length=100)),
                ('primary_maintainer', models.CharField(max_length=100)),
                ('condition_field', models.FloatField()),
                ('inspection', models.DateField()),
                ('bridge_length', models.FloatField()),
                ('curb_to_curb', models.FloatField()),
                ('deck_area_field', models.FloatField()),
                ('aadt', models.FloatField()),
                ('year_of_aadt', models.IntegerField()),
                ('gtms_mater', models.CharField(max_length=100)),
                ('gtms_structure', models.CharField(max_length=100)),
                ('year_built', models.IntegerField()),
                ('posted_load', models.FloatField()),
                ('restricted', models.FloatField()),
                ('r_posted', models.CharField(max_length=3)),
                ('other', models.FloatField()),
                ('other_post', models.CharField(max_length=111)),
                ('posted_leg', models.CharField(max_length=1)),
                ('posting_co', models.FloatField()),
                ('total_hz_c', models.FloatField()),
                ('total_hz_1', models.FloatField()),
                ('posted_vrt', models.FloatField()),
                ('posted_v_1', models.FloatField()),
                ('state_owned', models.CharField(max_length=3)),
                ('permitted_field', models.FloatField()),
                ('permitted_1', models.FloatField()),
                ('carried_la', models.CharField(max_length=134)),
                ('the_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
