# Generated by Django 2.2.3 on 2019-07-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newyorkbridge',
            name='inspection',
            field=models.DateField(null=True),
        ),
    ]
