# Generated by Django 2.2.3 on 2019-07-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0002_auto_20190713_0142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newyorkbridge',
            name='object_id',
        ),
    ]
