# Generated by Django 2.2.3 on 2019-07-13 12:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0003_remove_newyorkbridge_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newyorkbridge',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newyorkbridge',
            name='edited_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
