# Generated by Django 2.2.3 on 2019-07-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0004_auto_20190713_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newyorkbridge',
            name='common_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='other_post',
            field=models.CharField(blank=True, max_length=111),
        ),
    ]
