# Generated by Django 2.2.3 on 2019-07-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0005_auto_20190721_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newyorkbridge',
            name='carried',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='carried_la',
            field=models.CharField(blank=True, max_length=134),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='county_name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='crossed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='crossed_mi',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='crossed_to',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='gtms_mater',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='gtms_structure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='local_bridge',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='location',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='political_field',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='posted_leg',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='r_posted',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='region',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='newyorkbridge',
            name='state_owned',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
