# Generated by Django 2.2.4 on 2019-11-10 20:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0007_newyorkbridge_drive_time_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newyorkbridge',
            name='drive_time_queries',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
