# Generated by Django 3.0.2 on 2020-01-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0008_auto_20191110_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newyorkbridge',
            old_name='gtms_mater',
            new_name='gtms_material',
        ),
    ]
