# Generated by Django 2.2.3 on 2019-07-07 20:10

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('tag_key', models.TextField(blank=True, null=True)),
                ('tag_value', models.TextField(blank=True, null=True)),
                ('priority', models.FloatField(blank=True, null=True)),
                ('maxspeed', models.FloatField(blank=True, null=True)),
                ('maxspeed_forward', models.FloatField(blank=True, null=True)),
                ('maxspeed_backward', models.FloatField(blank=True, null=True)),
                ('force', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'configuration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsmNodes',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_value', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'osm_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsmRelations',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('members', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_value', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'osm_relations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OsmWays',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('members', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_value', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'osm_ways',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pointsofinterest',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('vertex_id', models.BigIntegerField(blank=True, null=True)),
                ('edge_id', models.BigIntegerField(blank=True, null=True)),
                ('side', models.CharField(blank=True, max_length=1, null=True)),
                ('fraction', models.FloatField(blank=True, null=True)),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_value', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('new_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'pointsofinterest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ways',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('reverse_cost', models.FloatField(blank=True, null=True)),
                ('cost_s', models.FloatField(blank=True, null=True)),
                ('reverse_cost_s', models.FloatField(blank=True, null=True)),
                ('rule', models.TextField(blank=True, null=True)),
                ('one_way', models.IntegerField(blank=True, null=True)),
                ('oneway', models.TextField(blank=True, null=True)),
                ('x1', models.FloatField(blank=True, null=True)),
                ('y1', models.FloatField(blank=True, null=True)),
                ('x2', models.FloatField(blank=True, null=True)),
                ('y2', models.FloatField(blank=True, null=True)),
                ('maxspeed_forward', models.FloatField(blank=True, null=True)),
                ('maxspeed_backward', models.FloatField(blank=True, null=True)),
                ('priority', models.FloatField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'ways',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WaysVerticesPgr',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('eout', models.IntegerField(blank=True, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('cnt', models.IntegerField(blank=True, null=True)),
                ('chk', models.IntegerField(blank=True, null=True)),
                ('ein', models.IntegerField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'ways_vertices_pgr',
                'managed': False,
            },
        ),
    ]
