# Generated by Django 2.2.3 on 2019-07-21 10:49

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('tag_key', models.TextField(blank=True, null=True)),
                ('tag_value', models.TextField(blank=True, null=True)),
                ('priority', models.FloatField(blank=True, null=True)),
                ('maxspeed', models.FloatField(blank=True, null=True)),
                ('maxspeed_forward', models.FloatField(blank=True, null=True)),
                ('maxspeed_backward', models.FloatField(blank=True, null=True)),
                ('force', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'configuration',
            },
        ),
        migrations.CreateModel(
            name='OsmNodes',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_value', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'osm_nodes',
            },
        ),
        migrations.CreateModel(
            name='OsmRelations',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('members', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_value', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'osm_relations',
            },
        ),
        migrations.CreateModel(
            name='OsmWays',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('members', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_value', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'osm_ways',
            },
        ),
        migrations.CreateModel(
            name='Pointsofinterest',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('vertex_id', models.BigIntegerField(blank=True, null=True)),
                ('edge_id', models.BigIntegerField(blank=True, null=True)),
                ('side', models.CharField(blank=True, max_length=1, null=True)),
                ('fraction', models.FloatField(blank=True, null=True)),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('attributes', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tags', django.contrib.postgres.fields.hstore.HStoreField(null=True)),
                ('tag_name', models.TextField(blank=True, null=True)),
                ('tag_value', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('new_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'pointsofinterest',
            },
        ),
        migrations.CreateModel(
            name='WaysVerticesPgr',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('eout', models.IntegerField(blank=True, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('cnt', models.IntegerField(blank=True, null=True)),
                ('chk', models.IntegerField(blank=True, null=True)),
                ('ein', models.IntegerField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'ways_vertices_pgr',
            },
        ),
        migrations.CreateModel(
            name='Ways',
            fields=[
                ('gid', models.BigAutoField(primary_key=True, serialize=False)),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('length_m', models.FloatField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('reverse_cost', models.FloatField(blank=True, null=True)),
                ('cost_s', models.FloatField(blank=True, null=True)),
                ('reverse_cost_s', models.FloatField(blank=True, null=True)),
                ('rule', models.TextField(blank=True, null=True)),
                ('one_way', models.IntegerField(blank=True, null=True)),
                ('oneway', models.TextField(blank=True, null=True)),
                ('x1', models.FloatField(blank=True, null=True)),
                ('y1', models.FloatField(blank=True, null=True)),
                ('x2', models.FloatField(blank=True, null=True)),
                ('y2', models.FloatField(blank=True, null=True)),
                ('maxspeed_forward', models.FloatField(blank=True, null=True)),
                ('maxspeed_backward', models.FloatField(blank=True, null=True)),
                ('priority', models.FloatField(blank=True, null=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('source', models.ForeignKey(blank=True, db_column='source', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wayssource', to='routing.WaysVerticesPgr')),
                ('source_osm', models.ForeignKey(blank=True, db_column='source_osm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wayssourceosm', to='routing.WaysVerticesPgr')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='routing.Configuration')),
                ('target', models.ForeignKey(blank=True, db_column='target', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waystarget', to='routing.WaysVerticesPgr')),
                ('target_osm', models.ForeignKey(blank=True, db_column='target_osm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waystargetosm', to='routing.WaysVerticesPgr')),
            ],
            options={
                'db_table': 'ways',
            },
        ),
        migrations.CreateModel(
            name='DriveTimeQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=300)),
                ('place_id', models.BigIntegerField(blank=True, null=True)),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('bounding_box', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=4)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('osm_class', models.CharField(blank=True, max_length=30)),
                ('osm_type', models.CharField(blank=True, max_length=30)),
                ('importance', models.FloatField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('edited_time', models.DateTimeField(auto_now=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('ways_vertices_pgr_start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.WaysVerticesPgr')),
            ],
        ),
        migrations.CreateModel(
            name='DriveTimePolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('drive_time_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.DriveTimeQuery')),
            ],
        ),
        migrations.CreateModel(
            name='DriveTimeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('seq', models.BigIntegerField(blank=True, null=True)),
                ('node', models.BigIntegerField(blank=True, null=True)),
                ('edge', models.BigIntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('agg_cost', models.FloatField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('edited_time', models.DateTimeField(auto_now=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('drive_time_query', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.DriveTimeQuery')),
                ('ways_vertices_pgr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.WaysVerticesPgr')),
            ],
        ),
    ]
