# Generated by Django 2.2.3 on 2019-07-10 09:37

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveTimeQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.CharField(max_length=300)),
                ('place_id', models.BigIntegerField(blank=True, null=True)),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('bounding_box', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=4)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('display_name', models.CharField(blank=True, max_length=300)),
                ('osm_class', models.CharField(blank=True, max_length=30)),
                ('osm_type', models.CharField(blank=True, max_length=30)),
                ('importance', models.FloatField(null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('edited_time', models.DateTimeField(auto_now=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='DriveTimePolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('drive_time_query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.DriveTimeQuery')),
            ],
        ),
        migrations.CreateModel(
            name='DriveTimeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('seq', models.BigIntegerField(blank=True, null=True)),
                ('node', models.BigIntegerField(blank=True, null=True)),
                ('edge', models.BigIntegerField(blank=True, null=True)),
                ('cost', models.FloatField(blank=True, null=True)),
                ('agg_cost', models.FloatField(blank=True, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('edited_time', models.DateTimeField(auto_now=True)),
                ('the_geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.DriveTimeQuery')),
                ('ways_vertex_pgr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routing.WaysVerticesPgr')),
            ],
        ),
    ]
