# Generated by Django 2.2.3 on 2019-07-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ways',
            name='osm_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
