# Generated by Django 2.2.3 on 2019-07-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_drivetimenode_drivetimepolygon_drivetimequery'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivetimequery',
            name='ways_vertices_pgr_start_point',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='routing.WaysVerticesPgr'),
            preserve_default=False,
        ),
    ]
