# Generated by Django 2.2.3 on 2019-07-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_auto_20190721_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivetimequery',
            old_name='ways_vertices_pgr_start_point',
            new_name='ways_vertices_pgr_source',
        ),
    ]
