# Generated by Django 2.2.3 on 2019-07-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_drivetimequery_ways_vertices_pgr_start_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={},
        ),
        migrations.AlterModelOptions(
            name='osmnodes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='osmrelations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='osmways',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pointsofinterest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ways',
            options={},
        ),
        migrations.AlterModelOptions(
            name='waysverticespgr',
            options={},
        ),
    ]
