# Generated by Django 2.2.3 on 2019-07-25 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_auto_20190721_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivetimepolygon',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
