# Generated by Django 2.2.4 on 2019-09-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_drivetimepolygon_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivetimequery',
            name='drive_time_hours',
            field=models.FloatField(null=True),
        ),
    ]
