# Generated by Django 2.2.3 on 2019-07-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_auto_20190713_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ways',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='waysverticespgr',
            options={'managed': False},
        ),
    ]
