# Generated by Django 2.2.4 on 2019-10-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_drivetimequery_drive_time_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivetimequery',
            name='pending_polygon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='drivetimequery',
            name='ways_vertices_pgr_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.WaysVerticesPgr'),
        ),
    ]
