# Generated by Django 2.2.3 on 2019-07-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_auto_20190713_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivetimenode',
            name='query_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='routing.DriveTimeQuery'),
        ),
    ]
