# Generated by Django 2.2.3 on 2019-07-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0006_auto_20190714_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivetimenode',
            old_name='query_id',
            new_name='drive_time_query',
        ),
    ]
