# Generated by Django 2.2.4 on 2019-11-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0007_auto_20191028_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivetimequery',
            name='polygon_pending',
            field=models.BooleanField(default=True),
        ),
    ]
