# Generated by Django 2.2.3 on 2019-07-16 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0007_auto_20190714_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivetimenode',
            old_name='ways_vertex_pgr',
            new_name='ways_vertices_pgr',
        ),
    ]
