# Generated by Django 2.2.4 on 2020-01-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0008_auto_20191116_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivetimepolygon',
            name='edited_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
