service: new-drive-time-query

provider:
  name: aws
  runtime: python3.7
  memorySize: 256

functions:
  index:
    handler: handler.hello
    events:
      - http: GET hello

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true
